name: "Build & Push"

on:
  push:
    branches:
      - 'main'
      - 'release/*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      TTL_REPO_NAME: ecp_equipment_service
      TTL_REPO_DURATION: 1h
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v1

      - name: "Set up JDK 17"
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: "Build with Maven"
        run: mvn clean package

      - name: "Build docker image"
        run: |
          IMAGE_TAG=ttl.sh/${{ env.TTL_REPO_NAME }}:${{ env.TTL_REPO_DURATION }}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          docker build -t ${IMAGE_TAG} .

      - name: "Push docker image ${{ env.IMAGE_TAG }}"
        run: |
          docker push ${IMAGE_TAG}